apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: rocket
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: vincenup/mrrobot:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      # imagePullSecrets:
      #   - name: misecreto1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: rocket
spec:
  # type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 80
